# Generated by Django 6.0.5 on 2026-05-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
