# Generated by Django 6.0.5 on 2026-05-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(),
        ),
    ]
